### ISSUE TITLE
Home, Full-Screen widgets & up-top menus overlaps 

### ISSUE THREAD

**Issue by Blockr22** [jurialmunkey/skin.arctic.horizon.2#667] opened 2022-11-22 22:26 UTC
### Skin section

Home Widgets

### Current Behavior

So the issue is whenever i play any video from home widgets & stop it after any amount of time, widgets & menus up top overlaps.
I have fen setup for full screen widgets, Home widgets with 3 tabs like - Trending, premier & 1 more & sub menu’s.

### Expected Behavior

It should work like we first launch kodi & the skin loads, no overlapping.

### Steps To Reproduce

1. Play any video(movie or show) from home widgets & stop after any amount of time.
2. Wait for the skin to load everything again if not already loaded & see for yourselves the overlapping.

### Screenshots and Additional Info

1. I have to press down twice for it to get normal.
2. Having this same issue on my multiple devices like - Nvidia shield 2017, Tcl C725 Android Tv & my windows 11 laptop 
3. Everything is up-2 date
4. Also have tried from scratch on my tcl tv & same issue with this skin
5. By d way great job on this skin, luv your work, keep it up.
6. Have jumped from Auramod skin, no issue in that skin but this one looks more futuristic.
![BC8DDE1C-7293-4247-920A-2E415FE5E7C1](https://user-images.githubusercontent.com/96648629/203433863-f0d4eaf7-9f4d-4e02-93c1-8f325000f43d.jpeg)
![854F96C2-6E6D-43C4-964B-DAB0BD56A6C0](https://user-images.githubusercontent.com/96648629/203433865-c9a807b9-913c-4ce9-94ec-68663716cad1.jpeg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-11-22 23:29
Duplicate of https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/601

**Closed by jurialmunkey** 2022-11-22 23:29 UTC
Labels: bug

**Comment by Blockr22** [comment] 2023-03-08 17:27
Hey @jurialmunkey i think i have found the problem & have commented the problem in #601 . If u could have a look at it, whenever u have time, would be great. Its the autoclose OSD setting.
