### ISSUE TITLE
Seren remaining unwatched episodes number not displaying 

### ISSUE THREAD

**Issue by leemacca13** [jurialmunkey/skin.arctic.horizon.2#738] opened 2023-01-09 02:05 UTC
### Skin section

Home Widgets

### Current Behavior

So I have the option to show remaining unwatched episodes numbers checked in the seren addon. But if I setup a widget for next up the number of episodes remaining does not show. But does for shows I have added to my watchlist. I have tried using the Auramod skin and it seems to work fine just seems to be an issue when using the AH2 skin. 

### Expected Behavior

Usually the number of episodes remaining of each show in the next up section of the seren addon will be displayed once a widget has been setup to show the next up list. 

### Steps To Reproduce

1. In the Seren setting in general enable to show remaining unwatched season episodes in mixed lists. 
2 create a widget to show the next up section of seren. 
3 once done return to the Home Screen and shows should now be displayed but without the number of episodes remaining. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-02-12 07:01
Duplicate of #726

**Closed by jurialmunkey** 2023-02-12 07:02 UTC
Labels: bug
