### ISSUE TITLE
[BUG] [Home menu] Returning to the home page after episode completion displays the window one row too low

### ISSUE THREAD

**Issue by Weevild** [jurialmunkey/skin.arctic.horizon.2#164] opened 2022-06-14 00:39 UTC
**Describe the bug**
Excuse that vague title. To further elaborate: when I've completed an episode and return to the home page I'll find myself with something looking like this:
![AH2 bug](https://user-images.githubusercontent.com/89477083/173469153-ca6098f2-f8b8-4eab-9a7a-804e2ba0f1df.jpg)
Where the object selector (don't know the name for the blue highlighted thingy) is way up there where my 'next up' episodes are but the window is misplaced so that it's one row below. I always have to go to the top of the menu which is somewhat bothersome.

**To Reproduce**
1. Finish an episode 
2. Long-press the 'back' button (on your remote if you have one) so that the player is closed
3. You should now have a home page which looks like mine in the screenshot.

**Expected behavior**
The window should be one row up where the blue selector is in my screenshot where my 'next up' episodes are.

**Screenshots**
Provided further up in relevant context.

**Platform Information (please complete the following information):**
 - Platform: Android TV (Shield Experience 9.0.3)
 - Skin Verision: 0.1.37

**Comment by jurialmunkey** [comment] 2022-06-17 08:37
I know exactly the bug you're talking about. I'm not sure if there's a solution though because the positioning is mostly handled by Kodi. I'm fairly sure it happens when a widget container ends up hidden due to not having items - because stopping a video forces Kodi to refresh the containers the positioning gets thrown off when the container is updating.

**Comment by jurialmunkey** [comment] 2022-07-07 15:46
@Weevild Are you still having this issue on recent versions? I haven't had it happen to me last few days since v0.2.26 so I think I _might_ have fixed it. However, also possible I've just been lucky, as I'm still not quite certain why it was happening in the first place.

**Comment by Weevild** [comment] 2022-07-08 17:44
@jurialmunkey Unfortunately yes I still do. Though I haven't upgraded (or used Kodi for that matter) for a while since I've set up my own new media server. So I had to do a local database reset and then upgrade from version 0.2, though I doubt this has anything to do with it persisting. I've gotten another bug though with version 0.2.32 (couldn't upgrade to .33 since I needed the newest TMDBHelper plugin which wasn't available on github, might want to upload that one, version .5) where the "play" and "more information" highlighted buttons are only filled 40% blue.

**Comment by Weevild** [comment] 2022-07-08 17:46
It might work if I just do a complete fresh install and don't use backup files which I've done earlier, but I'm going away for a week so I can't report back if that fixes it. It's a good possibility its a bug stemming from my configs from earlier builds.

**Comment by jurialmunkey** [comment] 2022-07-10 02:10
The split button issue should be fixed on a restart
as long as you installed new version of texturemaker. Otherwise you can force it to rebuild the textures by selecting a colour in skin settings.

Also not surprised if the position issue is still there. Just haven't been able to reproduce myself in a while so not quite sure the cause and just had a vague hope maybe I fixed it inadvertently.

**Closed** 2022-10-16 03:19 UTC
Labels: bug, external issue
