### ISSUE TITLE
[BUG] Watched Flags not showing on video addons (eg iPlayer WWW)

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#294] opened 2022-06-29 11:55 UTC
### Current Behavior

When an episode has been watched via an addon such as iPlayer WWW, the watched flag is not displayed - on Arctic Horizon a tick mark was displayed in this case.

### Expected Behavior

The tick mark should be displayed (as in Arctic Horizon)

### Steps To Reproduce

Watch any episode, or flag as watched - the watched flag is not displayed

### Screenshots and Additional Info

![screenshot00002](https://user-images.githubusercontent.com/67786207/176430413-e9954cc4-c705-477f-a49f-6b88358a43fc.png)
![screenshot00003](https://user-images.githubusercontent.com/67786207/176430509-9d66a772-dc20-4230-9d32-48e9c8b7d2f9.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-06-29 12:41
Duplicate of #249

**Closed by jurialmunkey** 2022-06-29 12:41 UTC
Labels: bug
