### ISSUE TITLE
[BUG] Widgets getting messed up on stopping video in the middle of playback

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.horizon.2#601] opened 2022-11-06 02:24 UTC
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

If I stop the video playback in the middle then the widgets on the home screen are getting totally messed up and overlapping with each other as shown in the attached screenshot. If I press the back button twice after that then the widgets become proper again. I'm using an Nvidia Shield TV Pro. Could you please check and advise?

### Expected Behavior

When stopping the playback of a video in the middle the widget alignment shouldn't get messed up and overlap with each other.

### Steps To Reproduce

Go to any home screen widget probably in the middle like a big landscape widget, etc. Play a video from there and press stop after sometime in the middle of the playback. On returning to the home screen the widgets will get totally messed up and overlap with each other. You then need to press the back button twice to return to the original widget alignment.

### Screenshots and Additional Info

![IMG20221106005521](https://user-images.githubusercontent.com/65297828/200151058-d27e1fae-bac3-4f84-8bd5-9d3dc0476f0d.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-11-06 04:56
I can't reproduce. Works fine for me.

**Comment by ShibajiCh** [comment] 2022-11-06 13:59
Hi @jurialmunkey,

Please try to replicate my scenario and see if it happens to you too. Keep a big landscape widget between 2 poster widgets, all in flix view. Then play any video from the big landscape widget. Forward or rewind the video a bit and then stop it's playback by clicking on the stop button in the OSD. After that it will return to the home screen. Wait for a few seconds until the widgets refresh. The widgets will misalign and overlap with each other as shown in the below screenshot. To return to the proper alignment, press back button followed by down arrow. Hope this will show you the same issue which I'm facing.

![IMG20221106192358](https://user-images.githubusercontent.com/65297828/200175000-95854fca-9071-47aa-b7fa-fe68107ea37e.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by krzysztofwinnik** [comment] 2022-11-06 15:48
I've noticed this too some time ago (like when new full expanded widgets were introduced or so). It happened to me 10 times or less - anyway, rarely enough not to open an issue.

**Comment by saxoloman** [comment] 2022-11-08 19:04
Happens to me like once a day.but its realy hard to reproduce

**Comment by rapteev** [comment] 2022-11-09 09:56
Hi
Also happens to me. Randomly after stop playback. I’m also on Nvidia shield

**Comment by Liquidrag** [comment] 2022-11-17 14:07
This happens to me and also this 
<img width="1281" alt="Screen Shot 2022-11-17 at 7 59 06 AM" src="https://user-images.githubusercontent.com/43726430/202467335-59772594-3520-4600-a882-c4b48c95f64d.png">
happens too. Both on my mac and shield.  I have the fullscreen widget then my regular widgets under.

**Comment by Mycale11** [comment] 2022-11-19 11:23
This happens every time I finish an episode from my next episode widget. I think it has to do with the big landscape widget style. 

To reproduce (I’m using a nvidia shield)
First widget on main menu is set to big landscape style, tmdbhelper>Trakt>next episodes
Then I have three poster widgets below, all tmdbhelper tv widgets.
Flixart is enabled. 

After playing an episode from the next episodes widget (either by the episode ending, or hitting stop) the widgets on the main menu will overlap, and the flixart will disappear. It happens just about every time for me. 

I also have a movie menu tab set up the same way, but all poster style widgets. I don’t think the overlap issue happens after playback there, though. Just in the tv menu.

**Comment by Blockr22** [comment] 2023-01-31 23:38
Still happening every time u stop any video. Using latest updates, any ETA on this bug ?

**Comment by jurialmunkey** [comment] 2023-02-01 02:13
> Still happening every time u stop any video. Using latest updates, any ETA on this bug ?

I havent been able to reproduce it (not doubting it happens - just I can't fix what I can't reproduce).

**Comment by Blockr22** [comment] 2023-02-01 03:07
@jurialmunkey should i send u kodi backup folder, if u wana have a look at it. My main setup is on shield 2017 but also have it on windows 11 & GTV Chromecast and tcl C725 android tv & windows 11 laptop. All have same issues, i tried fresh install but still didn’t help. I will remove my accounts info & can send u the .kodi folder if u can have a look & fix this bug.

**Comment by ShibajiCh** [comment] 2023-02-01 09:23
Hi @jurialmunkey and @Blockr22,

I can confirm too that this issue is still happening.

Thanks and Regards,
ShibajiCh.

**Comment by Blockr22** [comment] 2023-03-06 06:33
Hey @jurialmunkey so i was able to figure out what’s causing this issue. Recent updates reset some settings of the skin to default & the issue got fixed automatically. So i tried to setup the skin my way & started encountering same issue again so i tried turning things back one by one & found that in

Skin Settings-> Behaviour-> Autoclose OSD after X Seconds  is causing the issue.
Turning it off fixes it.

i hope u can fix this issue in next update. This feature is pretty handy but this bug is here since i m using the skin.

**Comment by Blockr22** [comment] 2023-03-08 17:22
Hey, so can anyone else having this issue confirm that toggle off autoclose OSD fixes this bug. I tried on windows 11 & shield 2017 & it fixes it for me on both devices

**Comment by jurialmunkey** [comment] 2023-03-08 23:39
@Blockr22 - I'm still unable to replicate with this setting enabled (in fact I'm fairly sure I've had it enabled the whole time).

**Comment by jurialmunkey** [comment] 2023-03-08 23:55
Likely what is happening is the automatic Close command is triggerring after the OSD has already closed due to stopping playback. That will then be interferring with where focus is and causing Kodi to get stuck in an unfocused state where no control has true focus.

When an expanded widget loses focus it clears the properties for the widget slide on expanding and, as a result, the skin engine won't know how to handle the expanded widgets anymore (widget is focused visibly but properties cleared internally)

Above commit should prevent that happening by cancelling the clock on the command.

**Comment by Blockr22** [comment] 2023-03-09 17:40
Hey so, do i have to do something or it will be updated in the new update?
I m not sure what that commit means

**Comment by xyzfre** [comment] 2023-03-09 20:43
It means it will be available when he up updates the repo

**Comment by Blockr22** [comment] 2023-03-09 22:40
Kk, so have to wait for another update of the skin ?

**Comment by jurialmunkey** [comment] 2023-03-09 22:49
Or install directly from main branch zip

https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/main.zip

**Comment by Blockr22** [comment] 2023-03-09 23:31
Got it, thnx

**Comment by Blockr22** [comment] 2023-03-12 08:38
Hey, i can confirm that the latest update from today fixed this issue & is working flawlessly. I think we can close this issue now. Thnx dev🙏

**Closed** 2023-03-12 09:08 UTC
Labels: bug

**Comment by AakashC2020** [comment] 2023-03-12 14:50
Thank you @jurialmunkey and @Blockr22 for resolving this issue!

**Comment by Blockr22** [comment] 2023-03-17 06:35
Hey dev @jurialmunkey so after few days of testing this bug is still happening but not everytime. Like once in few tries. Whatever u did helped alot but is not totally resolved. Can u have a look & make this go away for good ?
Thnx

**Comment by Blockr22** [comment] 2023-12-13 19:48
Hey dev, so this issue is back for me for few days now & happening a-lot more than before when i stop any playing video.
