### ISSUE TITLE
Autoclosing OSD on Nvidea Shield is not working

### ISSUE THREAD

**Issue by Aaiemron** [jurialmunkey/skin.arctic.horizon.2#114] opened 2022-06-09 05:03 UTC
Autoclosing OSD on Nvidia Shield is not working. The pause/play button stays focused and it's not autoclosing after a few seconds,

**Comment by jurialmunkey** [comment] 2022-06-09 06:28
Duplicate of #30

**Closed by jurialmunkey** 2022-06-09 06:28 UTC
