### ISSUE TITLE
[Feature] Colorbutton Support for Kodi 20

### ISSUE THREAD

**Issue by umbrellaplug** [jurialmunkey/skin.arctic.horizon.2#743] opened 2023-01-10 20:59 UTC
### Skin section

Other

### Feature description

Are you planning on adding any support for the new colorbutton setting introduced in Kodi 20?
Thanks!

### Why is this feature needed? Please justify and explain.

Before I use this new setting in an addon, I wanted to make sure skin authors would be supporting it.

### Screenshots and Additional Info

```
type="colorbutton"

colorbutton type settings allow a user to open a color picker dialog to select a color from Kodi's default color list. When the color has been selected, you can preview the colour and the hex code.

Note: Available from Kodi v20

<setting id="test36.color" type="string" label="32035" help="">
	<level>0</level>
	<default>FF000000</default> <!-- Black -->
	<control type="colorbutton" />
</setting>
```

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2023-01-10 23:22
Yes definitely will be supported, just have been delaying adding nexus only features temporarily to see the how the upstream elementtree problems pan out. Developments last few days upstream are looking positive so I'll probably be starting on nexus only features very soon. 

This is actually a duplicate of https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/681 as it is the same dialog. So ill close this issue to keep it to one issue to track.

**Closed by jurialmunkey** 2023-01-10 23:22 UTC
Labels: enhancement

**Comment by jurialmunkey** [comment] 2023-01-11 01:16
Actually I think I can implement this now without affecting Matrix at all.

Looking at the changes in Estuary it seems to be an entirely separate dialog and control type, so it wont change any Matrix behaviour by implementing it -- Matrix will just ignore the new xml.
