### ISSUE TITLE
[BUG] Various Linux Crashes w/ Nested Includes

### ISSUE THREAD

**Issue by cdelledonne** [jurialmunkey/skin.arctic.horizon.2#344] opened 2022-07-17 14:56 UTC
### Skin section

Other

### Current Behavior

Hi, I've just installed the skin with its dependencies. Kodi is crashing when I try to customise the skin's menus (e.g. when I click on "Customise home menu"). Here's a debug log, I hope it helps: https://paste.kodi.tv/oyasasusih.kodi,

### Expected Behavior

No crash.

### Steps To Reproduce

Settings > Skin > Customise home menu

### Screenshots and Additional Info

System info:
- OS: Fedora Linux 36 (seems to happen on Arch Linux too)
- System python version: 3.10.5
- Kodi version: 19.4

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by cdelledonne** [comment] 2022-07-17 15:03
EDIT: I had forgotten to add a title, sorry :)

**Comment by jurialmunkey** [comment] 2022-07-18 02:38
I see you're on Fedora. Sounds similar to an issue @chcore was experiencing on Arch https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/156#issuecomment-1186112728

These distros use the latest system version of python rather than Kodi's bundled version (ie they use 3.10.5 when latest Matrix bundles 3.8.5 of python). I think there is some issue with the skinshortcuts+kodi+3.10py combo because these crashes don't occur on other systems (there was a different crash that was resolved and since then things have been stable *except* on these Linux distros).

Not sure what the exact cause is yet but fairly sure it is skinshortcuts related rather than something the skin is specifically doing.

**Comment by chcore** [comment] 2022-07-18 09:41
As you've guessed @jurialmunkey, I now also experience this crash after being able to reach the configuration menu in the latest version. I've attached a crash log if it helps.

[kodi_crashlog-20220718_193913.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9130950/kodi_crashlog-20220718_193913.log)

**Comment by AstaFatherSatan** [comment] 2022-07-28 14:04
Same here

**Comment by jurialmunkey** [comment] 2022-07-29 14:38
@cdelledonne @chcore - Could you please test v0.3.2 for me?
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.3.2

I installed Fedora on a VM and was able to reliably recreate this crash and track down what piece of skin code was causing it. That being said, I have absolutely no idea why this particular piece would cause a crash here.

Anyway, I switched to an alternative method which does practically exactly the same thing as a workaround and it appears to work. Some deeper issue with how Kodi does nesting in includes, so not really a skin bug per se - but the workaround works at least...

**Comment by dsadsadasdasdas** [comment] 2022-07-29 17:33
Version 0.3.2 fixed it on Arch for me. Thank you very much!

**Comment by chcore** [comment] 2022-07-29 18:51
Thanks @jurialmunkey this is some progress, but I am still able to trigger crashes by doing the following:

1. Delete `skin.arctic.horizon.2`, `script.skinshortcuts` and `script.skinvariables` in `addon_data` to start from a clean slate
2. Start Kodi and go to Configure Skin > Appearance > Customise appearance
3. Choose the Performance setting for Background and Title and then Close
4. Go back to the home screen, and Kodi will crash. I'm not able to get Kodi to start up again without deleting `skin.arctic.horizon.2` in `addon_data`

**Comment by chcore** [comment] 2022-07-29 18:56
Here is another type of crash:

1. Delete `skin.arctic.horizon.2`, `script.skinshortcuts` and `script.skinvariables` in `addon_data` to start from a clean slate
2. Start Kodi and go to Configure Skin > Appearance > Customise colours > Customise
3. Choose Flat (No Gradient) and Kodi will crash
4. Restart Kodi and try to go to Configure Skin, which will trigger another crash

**Comment by jurialmunkey** [comment] 2022-07-30 05:46
This is a problem with the skinning engine on Linux using `<nested />` includes. The skin isn't doing anything wrong - there is a bug in the skinning engine. Trying to fix a significant bug like this with workaround is going to be a game of whack-a-mole.

Please confirm if this issue happens on latest Nexus nightly. If the crashing doesn't occur in Nexus then there's no point me trying to find workarounds. However, if the crash is still there then a bug report needs to be filed to get it fixed.

Also FYI note that Nexus currently has a widget display issue bug. There is a fix for this bug but the PR hasn't been merged yet - so Nexus is not suitable *yet* for daily use with this skin but once that fix is in it will be.

**Comment by dsadsadasdasdas** [comment] 2022-07-30 20:44
I am still crashing on startup when loading skinshortcuts.
[kodi_crashlog-20220730_223547.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9227555/kodi_crashlog-20220730_223547.log)

Skin: v0.3.4
Kodi: v20.0-ALPHA2
Python: 3.10.5
Kernel: 5.18.14-zen1-1-zen
OS: EndeavourOS

**Comment by chcore** [comment] 2022-08-01 11:18
@jurialmunkey I can confirm the two crashes occur on v20 master. I'm not sure I have the necessary knowledge to file a useful bug report on the Kodi repor for it though.

**Comment by jurialmunkey** [comment] 2022-08-01 12:21
Thanks both for testing and confirming.

> @jurialmunkey I can confirm the two crashes occur on v20 master. I'm not sure I have the necessary knowledge to file a useful bug report on the Kodi repo for it though.

@chcore - No no that's great! I can setup another VM and install Linux Mint to knock together a test cast for Nexus. Just the Fedora install I originally did is really sluggish and a bit of a pain to work on -- and I didn't want to go to the trouble of setting up a clean install with a new VM if it was working okay in Nexus for you guys.

In the meantime I should be able to add some workarounds in the skin since I'm pretty sure what the underlying cause is now (just might take me a while to find all the spots where I'm using that method).

**Comment by AstaFatherSatan** [comment] 2022-08-05 12:30
Thank you everyone

**Comment by jurialmunkey** [comment] 2022-08-06 04:48
I still haven't been able to create a reliable testcase in Estuary. 

I've narrowed the general cause of the crash down to the nested includes changing the default textures of the togglebutton control. However, the crash occuring appears to rely on a very specific set of circumstances which happen in AH2 that I haven't been able to pinpoint yet. 

So in the meantime, I guess a game of whack-a-mole it is!

@cdelledonne @chcore @AstaFatherSatan - Could you please test v0.3.7 of the skin? On Linux Mint that solves all the crashes that I've been able to reproduce.

**Comment by cdelledonne** [comment] 2022-08-06 17:22
I'll start using v0.3.7 and report back in a few days in case there are any issues, or if all works well

**Comment by chcore** [comment] 2022-08-08 06:15
Thank you for your efforts @jurialmunkey but unfortunately both crashes https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/344#issuecomment-1199852384 and https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/344#issuecomment-1199856206 still occur for me.

**Comment by jurialmunkey** [comment] 2022-08-08 10:01
> Thank you for your efforts @jurialmunkey but unfortunately both crashes [#344 (comment)](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/344#issuecomment-1199852384) and [#344 (comment)](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/344#issuecomment-1199856206) still occur for me.

@chcore 
Ah damn. On Matrix or Nexus?

Is this only when deleting all the config? Possibly I didn't test that properly. I was able to reproduce the bug with the monochrome colour being on consistently so I assumed once that was fixed I'd fixed the issue -- but possibly there's another issue when resetting all the configs.

**Comment by jurialmunkey** [comment] 2022-08-08 14:49
@chcore - Please test v0.3.12 - That fixes the crash when setting background to None and font to Light for me.

**Comment by chcore** [comment] 2022-08-09 05:53
@jurialmunkey Thank you that seems to have worked! I can no longer reproduce either of those crashes.

**Comment by jurialmunkey** [comment] 2022-08-09 09:25
> @jurialmunkey Thank you that seems to have worked! I can no longer reproduce either of those crashes.

Yeah I ended up just going through and removing that method that I was using that was causing problems and reverting it to an older approach. It's less elegant of an approach in terms of skin code but if that's the cost for things being stable until I can figure out a reliable test case for Estuary and get someone to fix the underlying issue, then so be it.

I'm going to close this issue as I'm fairly sure this should resolve all these types of issues (and if there are other crashes it is going to be a different problem causing them). Feel free to open a new issue if you encounter other crashes

**Closed by jurialmunkey** 2022-08-09 09:25 UTC
Labels: bug
