### ISSUE TITLE
[Feature] Make "infotitle" wrapping optional.

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#618] opened 2022-11-08 19:00 UTC
### Skin section

Fonts and Languages

### Feature description

Make the feature introduced in v0.6.2 (https://github.com/jurialmunkey/skin.arctic.horizon.2/commit/984194d8e849c1527dec069c5cc69581580a4bbd) optional.

### Why is this feature needed? Please justify and explain.

The "infotitle" wrapping approach isn't very reliable, especially since there's no way to specify visually "pleasing" a line break position. Additionally, having a size of 58 for "font_infotitle_doublerow" breaks any typographic ratios against "font_mainlabel" (which were loose to begin with ;) ). 

### Screenshots and Additional Info

![screenshot00003](https://user-images.githubusercontent.com/4211774/200651927-7f4a92d0-fbcc-47ca-a3e1-c4fed22ab914.png)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2022-11-09 02:41
Are you sure you are using the most recent version of the skin? I cannot reproduce this wrapping issue.

![screenshot00087](https://user-images.githubusercontent.com/4618719/200723841-26bb77b7-6a87-4705-a23c-fd8e07ae5b09.jpg)

And yes there are still some adjustments that need to be made in finding a good ratio but the solution isn't throwing the baby out with the bath water via a setting.

**Comment by jurialmunkey** [comment] 2022-11-09 03:43
>  Additionally, having a size of 58 for "font_infotitle_doublerow" breaks any typographic ratios against "font_mainlabel" (which were loose to begin with ;) ).

This is a good point though. Made me realise I calculated it incorrectly.

It *should* be (n=5 r=2 base=32pt)
32 (menu) > 37 (midi) > 42 (main) > 49 (weather) > 56 (wrap) > 112 (title)
NOT
32 > 36 > 44 > 50 > 58 > 116

**Comment by jbelew** [comment] 2022-11-09 04:36
> Are you sure you are using the most recent version of the skin? I cannot reproduce this wrapping issue.
> 
> ![screenshot00087](https://user-images.githubusercontent.com/4618719/200723841-26bb77b7-6a87-4705-a23c-fd8e07ae5b09.jpg)
> 
> And yes there are still some adjustments that need to be made in finding a good ratio but the solution isn't throwing the baby out with the bath water via a setting.

Yes, the latest version ... Could be a Windows vs Linux GDI / Font rendering difference. I'll be patient for improvements, but it's something that gets to me enough that I end up manually tweaking the skin to disable it.

**Comment by jbelew** [comment] 2022-11-09 23:45
Another rendering issue, this time with long words is German. 
![screenshot00016](https://user-images.githubusercontent.com/4211774/200965900-e6f18c8a-bc8c-44ab-a2cb-4dc8991fae68.png)

**Comment by jurialmunkey** [comment] 2022-11-10 01:02
Are you testing on Matrix or Nexus? Because I don't get these problems and I think this must be a Linux rendering issue. There was some issue with how pixel widths were calculated on Linux on some cards that was fixed in Nexus.

Either way I guess there's probably no real way out other than a setting.

**Comment by jbelew** [comment] 2022-11-10 04:51
I'm on Nexus / Linux using Wayland (CoreElec specifically). The spacing evaluation seemed to get better with 6.8, but I was probably spending most of the time with my PR installed. Asides from the "Konzerthausorchester Berlin" issue, I spotted only two failed wrapping points while scanning quickly through my library. It's got to be some weird 1px issue. The "Godzilla vs. Kong" issue was just so glaring since that one popped up and was stuck there in one of my widgets over the past few days.

**Comment by jbelew** [comment] 2022-11-10 05:04
I just went through 1000+ titles with https://github.com/jurialmunkey/skin.arctic.horizon.2/pull/624 installed. Looks like the hidden box calculation is now working without issue.

**Closed** 2022-11-10 05:30 UTC
Labels: enhancement
