### ISSUE TITLE
Widget end row action no longer works.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.horizon.2#866] opened 2023-03-12 02:55 UTC
### Skin section

Home Widgets

### Current Behavior

Since 8.15 the widget end row action doesn't work. I have mine settiopen TMDB movies once you hit the last row of widgets and press down one more time.

But since the last update this no longer happens. 

### Expected Behavior

When the last row is shown, pressing down once should open the menu set at Widget end row action. See pic.
![20230312_025137](https://user-images.githubusercontent.com/97023369/224521513-2fd39b2d-339b-42b3-8f45-43bfaa921f72.jpg)

### Steps To Reproduce

Click last row once this should activate the new menu.

### Screenshots and Additional Info

Image attached showing the menu 
![20230312_025137](https://user-images.githubusercontent.com/97023369/224521587-4d5b229e-a11e-4011-b94a-474812cc73da.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-03-12 03:32
Duplicate of #857

**Closed by jurialmunkey** 2023-03-12 03:32 UTC
Labels: bug
