### ISSUE TITLE
[BUG] Repeated crashing with no user input

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#676] opened 2022-11-29 01:49 UTC
### Skin section

Other

### Current Behavior

The skin is not repeatedly crashing, while idle. I've played with TMDBHelper thread count (for the first time) to no avail. 

### Expected Behavior

Not to crash?

### Steps To Reproduce

Logs attached. 

[log-2022-11-29-01.37.47.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10109034/log-2022-11-29-01.37.47.zip)
[log-2022-11-29-01.37.28.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10109035/log-2022-11-29-01.37.28.zip)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-11-29 03:43
In both your logs, the last thing to do anything was the prime plugin -- plugin.video.amazon-test. Can you try disabling that first to make sure it isn't that plugin?

If the crash is still happening, let's first rule out skin changes by downgrading the skin to the last stable version that you remember using. You can find versions below 0.7.7 in this folder:
https://github.com/jurialmunkey/repository.jurialmunkey/tree/master/matrix/zips/skin.arctic.horizon.2

Install an old zip from a previous version that was stable for you then let it run and see if you're still getting crashes. If you are then lets try downgrading TMDbHelper next. You can find previous nexus versions here:
https://github.com/jurialmunkey/repository.jurialmunkey/tree/master/nexusrepo/zips/plugin.video.themoviedb.helper

If you the last stable version you remember using was before 5.0.27 then you can get zips for those from the matrix folder instead:
https://github.com/jurialmunkey/repository.jurialmunkey/tree/master/matrix/zips/plugin.video.themoviedb.helper

If we can figure out whether it is TMDbHelper or the skin, and approximately which version it started occurring then that will give some clues as to what the cause is.

If downgrading both to versions that were previously stable doesn't work, then it is likely an issue with another addon on your system (or Kodi itself).

**Comment by jurialmunkey** [comment] 2022-11-29 03:52
Also I noticed that you're running Python 3.11 and I'm not certain how that plays with PIL (the python image processing library used for blur and crop). Kodi on windows runs python 3.8.5. A lot of crashes encountered on Linux are often to do with conflicts between PIL and the python version running. You can get a sense of whether that's the problem by disabling both Blur and Crop -- you can use "Stretch" as a PIL-free alternative to blur with a similar effect. (And if you weren't using blur or crop already then we can rule out PIL issues as that's the only thing TMDbHelper uses that library for).

**Comment by jbelew** [comment] 2022-11-29 07:08
I've disabled the Prime plug-in, and saw that also, the same results. Regarding the Linux install, it's CoreElec, so the whole image is maintained by the dev team for compatibility. For PIL specifically, I am using stretch ... a good trade-off between performance and intended effect. As I'm typing this, it just bombed again after watching a movie. 

[log-2022-11-29-07.06.58.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10110571/log-2022-11-29-07.06.58.zip)

**Comment by jurialmunkey** [comment] 2022-11-30 01:47
I didn't think it would be the Prime plugin but was a bit too much of a coincidence to ignore ruling out first. Yep, if you're using stretch and not using clearlogos then that rules out a PIL issue as that's all it is used for (blurring and cropping).

The log isn't giving me much. Can you try downgrading the skin to the last stable version that you used? If the crash still happens with the skin downgraded then that'll point to some other issue either with TMDbHelper or Nexus itself.

**Comment by jbelew** [comment] 2022-11-30 02:25
I'll drop back to 7.6 and report back.

**Comment by jbelew** [comment] 2022-11-30 18:47
Looks like the last stable version for me was 0.7.7. I'll let it run a while then try 0.7.8 to confirm.

**Comment by jbelew** [comment] 2022-12-01 00:33
I've done a full mix of versions along with disabling most of the video addons. I'm back to the latest with only Netflix and Youtube active and it seems to be running better (famous last words).

**Comment by jbelew** [comment] 2022-12-01 03:34
I take that back ... Not as often, but two crashes in under 60 minutes. Seeing 'EXCEPTION: Non-Existent Control' messages.

[log-2022-12-01-03.33.20.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10129027/log-2022-12-01-03.33.20.zip)

**Comment by jurialmunkey** [comment] 2022-12-01 06:03
The Non-Existent control messages can be ignored - those won't cause a crash. That's just because you have disabled some lists in the recommendations window and TMDbHelper is checking which ones exist. Kodi logs the message for some reason even if the script correctly catches the exception in a try/except block and it doesn't get raised.

Log isn't giving me any clues really. Is there any particular pattern to when the crashes occur.

**Comment by jbelew** [comment] 2022-12-01 06:49
No real pattern, spend a few sessions of just browsing everything to try and trigger it. Seems like a memory leak type issue.

**Comment by naudski** [comment] 2022-12-01 06:53
I have done some testing too. I completely removed both AH2 and TMBHHelper and installed Embuary v2 mod with widgets using FEN and I still get crashes. Much less frequent though. My guess is there is definitely something wrong in the Nexus build after October 15th. We need to figure out what has changed after that release. It seems that AH2 and/or TMBHHelper is triggering that crash more often.
I am using Nexus on Shield Pro.

**Comment by jbelew** [comment] 2022-12-02 01:40
CoreElec didn't pull the latest Kodi package until last night, 113022. Prior to that, it's has been running the first B1 build for almost a month. 

https://github.com/CoreELEC/CoreELEC/commit/4233a98bb7

**Comment by jurialmunkey** [comment] 2022-12-04 01:20
Relatively confident this is the same issue as https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948 related to Libre/CoreELEC's implementation of python and a module used by TMDbHelper rather than the skin specifically.

Github doesn't have a way to merge two issues, so I'll close this one and discussion can continue in the other thread

**Closed by jurialmunkey** 2022-12-04 01:20 UTC
Labels: bug
