### ISSUE TITLE
[Feature] "Poster MediaInfo" view mode

### ISSUE THREAD

**Issue by 43v3rLoCo** [jurialmunkey/skin.arctic.horizon.2#398] opened 2022-08-03 01:34 UTC
### Skin section

Library Views

### Feature description

This is the view mode available in AuraMod that shows it as a poster wall, but with the media info on the left side of the highlighted selection. 

### Why is this feature needed? Please justify and explain.

I honestly think this to be one the of the best view modes. I'm always trying new skins, but this view mode is what always forces me back to AuraMod. After trying this theme, I really want to move on from Aura and stick with AH2, but this is the only thing that's really missing from it. 

### Screenshots and Additional Info

![screenshot00004](https://user-images.githubusercontent.com/13120383/182504259-ca13d381-6853-456f-96b4-5ab74c30093d.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2022-08-03 04:54
Duplicate of #320

**Closed by jurialmunkey** 2022-08-03 04:54 UTC
Labels: enhancement
