### ISSUE TITLE
[Feature] Osd Player 

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#306] opened 2022-07-02 11:19 UTC
### Is your feature request related to a problem? Please describe.

When I play a movie and it is of poor quality

### Describe the solution you'd like

Quality replacement of the movie or series with a click.
There will be a button, which will allow you to change a version of the movie or series
In MOVIE DB PLAYER

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2022-07-02 13:35
Duplicate of #241

**Comment by jurialmunkey** [comment] 2022-07-02 13:36
Please don't open duplicate requests.

**Closed by jurialmunkey** 2022-07-02 13:35 UTC
Labels: enhancement
