### ISSUE TITLE
Crashing with cleararts on

### ISSUE THREAD

**Issue by unicornsandcandies** [jurialmunkey/skin.arctic.horizon.2#630] opened 2022-11-10 18:35 UTC
### Skin section

Home Widgets

### Current Behavior

When I'm opening Kodi, widgets start loading and and they appear. When it happens, bold font show title is changing into clearart and Kodi crashes immediately. Everything works with bold font setting instead of clearart

### Expected Behavior

Kodi loading up widgets without any problem like it happens on my other devices

### Steps To Reproduce

1. Open Kodi
2. Wait for fullscreen tv show addon to load

### Screenshots and Additional Info

I'm using raspberry pi 4, it's the only device that has this issue currently, it has exact same setup as my two other devices

Log: https://pastebin.com/raw/1jX6MMeH

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-11-11 00:01
You're on Arch Linux so it almost certainly an issue with the version of python you have installed and PIL (which does image manipulations). 

These types of issues with PIL popup all the time for Linux distros because Linux overrides Kodi's version of python (3.8.5) with its own version. This result in unexpected behaviour with modules like PIL which use numpy. 

Possible fix in this comment https://github.com/jurialmunkey/skin.arctic.horizon/issues/452#issuecomment-1042448567

**Comment by unicornsandcandies** [comment] 2022-11-11 00:37
> You're on Arch Linux so it's almost certainly an issue with the version of python you have installed and PIL (which does image manipulations).
> 
> These types of issues with PIL popup all the time for Linux distros because Linux overrides Kodi's version of python with its own system version. This results in unexpected behaviour with modules like PIL which use numpy.
> 
> This comment suggests going from 3.9.7 to 3.9.8 of python will solve the issue [jurialmunkey/plugin.video.themoviedb.helper#581 (comment)](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/581#issuecomment-962455234)
> 
> I couldn't see from your log which point version of python 3.9 you have installed but if it it is 3.9.7 or lower then that'd be the issue and you should upgrade to a higher version of 3.9 (but _NOT_ 3.10.x as that has also had issues reported previously)
> 
> Another possible fix in this comment [jurialmunkey/skin.arctic.horizon#452 (comment)](https://github.com/jurialmunkey/skin.arctic.horizon/issues/452#issuecomment-1042448567)

I'm on raspberry pi os, it's debian based

**Comment by jurialmunkey** [comment] 2022-11-11 01:16
Sorry "Arch Linux" is just a stupid autocorrect on my phone.

The point applies to any Linux distro. Kodi will use the system version of python rather than its bundled version. Python 3.9 versions before 3.9.8 will conflict with how the PIL/pillow package uses numpy and will crash.

**Comment by unicornsandcandies** [comment] 2022-11-11 18:58
Okay it kinda works now. Cleararts are much smaller then on my other devices and sometimes have weird positioning, but it works

**Comment by jurialmunkey** [comment] 2022-11-14 06:35
Closing this as it isn't a skin issue but rather a python one.

**Closed by jurialmunkey** 2022-11-14 06:35 UTC
Labels: bug
