### ISSUE TITLE
[BUG] Autoscroll text overlap issue in cast info

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#178] opened 2022-06-15 13:43 UTC
The autoscroll summary text in cast info is overlapping with other texts. Please see below screenshots. Kindly resolve the issue when possible.
![IMG20220615191134](https://user-images.githubusercontent.com/65297828/173842274-f5c0975a-c012-46a0-9907-5855d051e453.jpg)
![IMG20220615190848](https://user-images.githubusercontent.com/65297828/173842300-fc4f71f4-b3e2-4270-94f1-d0854f16790f.jpg)

**Comment by jurialmunkey** [comment] 2022-06-15 13:51
Duplicate of #176

**Closed by jurialmunkey** 2022-06-15 13:51 UTC
Labels: bug
