### ISSUE TITLE
[BUG] Widget End Of Row Action doesn't work.

### ISSUE THREAD

**Issue by inihendrix** [jurialmunkey/skin.arctic.horizon.2#857] opened 2023-03-05 20:10 UTC
### Skin section

Home Widgets

### Current Behavior

Nothing happens when selecting an action for this feature, however the "Menu Up Action" does work.

### Expected Behavior

Worked as intended previous to update 😎

### Steps To Reproduce

1. Edit widgets by customizing home menu.
2. Choose an action for End Of Widget Row.
3. Try to use feature.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-03-05 23:14
It's working fine for me. I cannot reproduce this issue. If you had previously set actions you will need to set them again.

**Comment by inihendrix** [comment] 2023-03-06 07:57
I don't get it, I've been trying to get it to work but I just can't. No action seems to work for me as an End Row Action choice, and as a matter of fact, once an action is selected the skin doesn't even show a notification to let me know the skin has reloaded with the appropriate update.

However I can totally get the Up Menu Action to register a change, and have been using that to access my custom hub.

Is there anything you need from me to help better understand my particular issue? Is be happy to help!

**Comment by jurialmunkey** [comment] 2023-03-06 07:58
What version of skinshortcuts are you running?

**Comment by inihendrix** [comment] 2023-03-06 08:02
Version 2.0.3

**Comment by inihendrix** [comment] 2023-03-06 08:05
No I'm setting this on a normal set of widgets:

1. Submenu of Love TV guides
2. List of last played Live TV channels
3. YouTube videos
4. Trakt watched shows that have played in the past week

All these widgets are either landscape or poster variations as well.

What should I edit in the xml file? I'm fairly confident I can look for what you think might need fixing.

**Comment by jurialmunkey** [comment] 2023-03-06 09:05
> What should I edit in the xml file? I'm fairly confident I can look for what you think might need fixing.

Nothing to edit. The file is automatically generated by skinshortcuts based upon the templates the skin specifies. Everytime you see the notification in the top right that skinshortcuts is building, that's the file it is making based upon how you've set up your menus.

If you can upload it here then I can have a look and it should give me some indication of what skinshortcuts is outputting / why it isn't triggerring the ondown action.

You might need to put it in a zip file for git to allow you to upload it to a comment (I cant remember if git accepts xml filetype in comment uploads, but it definitely accepts zip).

**Comment by inihendrix** [comment] 2023-03-06 16:32
I'll look at it once I'm out of the office and back home 👍 thank you for helping me with this, I'm normally pretty good with fixing minor issues but this one is really confusing me haha!

**Comment by blakie1225** [comment] 2023-03-07 03:14
I also have this issue but only with my movies menu, my shows menu end of row action works fine. Where can I find the file that you need?

**Comment by inihendrix** [comment] 2023-03-07 06:52
[script-skinshortcuts.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10906256/script-skinshortcuts.zip)

Here you go jurialmunkey 👍

Btw I found that in the '720p' folder, however I changed the name of that folder to '1080i' and changed my gui to 1080. Honestly I don't think that made anything different, but I figured having a 720p folder just didn't seem correct.

Either way, would love to hear your feedback for what steps to take!  😎

**Comment by inihendrix** [comment] 2023-03-07 16:08
[script-skinshortcuts-includes.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10911426/script-skinshortcuts-includes.zip)

Apologies, here is the correct file 🤓

**Comment by blakie1225** [comment] 2023-03-07 21:17
[script-skinshortcuts-includes.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10914010/script-skinshortcuts-includes.zip)

**Comment by jurialmunkey** [comment] 2023-03-08 00:10
Thanks @inihendrix and @blakie1225 -- that was super helpful. Can see exactly what the problem is and should be fixed with latest git version (will be in next release just a few other things I need to update first).

Very strange bug in skinshortcuts though. I used a different method to set the "widgetEndRowAction" property for the item but instead of skinshortcuts updating the value of the existing property from the old method, it was making a new property with the same name.

Because the old property appeared first, skinshortcuts was still using that when building the template -- problem is the old property does nothing now because it's just a text label and the code to transform it into an action no longer exists (previously only had a set list of hardcoded action whereas now action is set directly).

**Comment by inihendrix** [comment] 2023-03-08 01:14
Awesome, I figured whatever the issues was, that you'd find it pretty quickly. That's strange that skinshortcuts would sort of go rogue like that haha. Looking forward to the update and always happy to help you make a great skin even better!

**Comment by inihendrix** [comment] 2023-03-09 01:45
@jurialmunkey I'm not sure if the latest update addressed the End Row Action issue, but I still cannot get it to work. Should I rebuild my home widgets and try again?

**Comment by jurialmunkey** [comment] 2023-03-09 01:48
> @jurialmunkey I'm not sure if the latest update addressed the End Row Action issue, but I still cannot get it to work. Should I rebuild my home widgets and try again?

You possibly might need to add the widget row action again. Other possibility is you might need to change something in your menu to trigger skinshortcuts to rebuild (e.g. change a label or move an item up/down etc).

**Comment by jurialmunkey** [comment] 2023-03-12 03:48
> @jurialmunkey I'm not sure if the latest update addressed the End Row Action issue, but I still cannot get it to work. Should I rebuild my home widgets and try again?

Are you using latest git master? The fix is not on the repo version yet. Since switching to Beta I'm not push releases immediately after any change (i.e. no "nightlies"). Im trying to limit to one or two releases a week to avoid continually updating machines. 

To get the most recent changes you either need to install from git master, or wait until I push a release (about to do one now).

**Comment by inihendrix** [comment] 2023-03-12 06:42
I actually had the time this evening to finally fresh install and set everything up again (I needed to since my PVR was a little disorganized) and now my End Widget Row works great! I also made a backup in case anything goes awry.

Your skin works amazingly and I bet oftentimes the issues are user end, but I genuinely appreciate your efforts to find solutions!

**Closed** 2023-03-12 07:13 UTC
Labels: bug
