### ISSUE TITLE
[BUG] 3 Important Skin sections im using are not loading there results on Kodi v20 (Nexus) Alpha2

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#347] opened 2022-07-18 23:57 UTC
### Skin section

Other:
 - Search Bar
 - Recommendations
 - Information Page 

### Current Behavior

Hey there, first off, i would like to say thank you for fixing issue widget reposition bug and widget not loading bug on nexus, here are three same or similar bugs that i am experiencing. 

 - 1st Bug: Whenever you use the search in the home menu bar, results are not loading at all. 
 
 - 2nd Bug: Pressing down from row view scrollbar to view Recommendations does not load the results.
 
 - 3rd Bug: Same as second bug except your on the information page of a movie or tv show and your pressing down to showing Cast, Similar, Ect.

### Expected Behavior

For all these three bugs i described up there to load there results in. 

### Steps To Reproduce

1. Download you a [Pre-release Build ](https://kodi.tv/download/windows) from the kodi website. 
2. Download your skin and tmdb helper as well
3. Customize your search menu to have tmdb helper results like Poeple, Movies, TV Shows, ect
4. Once your done customizing, search up anything on the home menu bar.
5. Notice the **1st bug** that no results are loading. 
6. Go to tmdb helper and hover over a movie or tv show and press down. 
7. Notice the **2nd bug** that no results are also loading.
8. Hover over a movie or tv show again but this time, go to context menu and go to information.
9. Once your one information press down.
10. Notice that you have found the **3rd bug** and nothing is loading.

### Screenshots and Additional Info

**Search Bar Bug**
![Tries to load Search Results Bug](https://user-images.githubusercontent.com/62456796/179635756-30b33cd3-f52a-4864-8c15-370b1e04a79d.png)
**Loading Cast Bug**
![Loading Cast Bug](https://user-images.githubusercontent.com/62456796/179635842-fc705bd4-7007-47ae-a9f4-eae9af24f387.png)
**Recommendations Bug**
![Recommendations Not Loading](https://user-images.githubusercontent.com/62456796/179635877-68acd167-a619-46d7-acd4-f3dd4b4619ad.png)

These are all the bugs i found so far on Kodi v20 (Nexus) Alpha2. If you could provide a fix for these bugs, that would be wonderful cause with Nexus, i have not experience any freezing with your skin at all when using this version. I have experience freezing on 19.4 due to me wanting automatic updates to work and specific versions. 
Thank you and hope these could get fixed. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Goldenfreddy0703** [comment] 2022-07-19 00:08
Very sorry for changing to title 3 times.

**Comment by jurialmunkey** [comment] 2022-07-19 01:07
Duplicate of #225

Skin is still broken on Nexus as the required PR to revert the breaking changes in GUI engine have not been merged. If you want to use nexus you must either use a build from before 5 June or wait until Alpha 3.

**Closed by jurialmunkey** 2022-07-19 01:07 UTC
Labels: bug

**Comment by jurialmunkey** [comment] 2022-07-19 01:11
See this comment for more details https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/225#issuecomment-1168865098

**Comment by Goldenfreddy0703** [comment] 2022-07-19 01:14
Ok, i will see if i can request a build from before 5 june. Thank you

**Comment by Goldenfreddy0703** [comment] 2022-07-19 01:27
Ok so im not sure what build to use but i think this was the build to Improving/fixing transparent control rendering. 

![image](https://user-images.githubusercontent.com/62456796/179643988-954cd388-3322-4fb8-92a6-a6aaf251b5e8.png)

I hope this one is correct, Thank you

**Comment by jurialmunkey** [comment] 2022-07-19 04:00
> Ok so im not sure what build to use but i think this was the build to Improving/fixing transparent control rendering.
> 
> ![image](https://user-images.githubusercontent.com/62456796/179643988-954cd388-3322-4fb8-92a6-a6aaf251b5e8.png)
> 
> I hope this one is correct, Thank you


Yes, that's the testbuild I generated for WIN64. It should fix the issue. However, it is **not** for Android (it is Windows 64bit). Also note that I built it before the most recent changes in the PR.

The fix in the PR has not been merged into main yet as there are still issues with dirty regions. There are no nightly builds with this fix in. You need to go back to Alpha 1 to get the skin working as that was prior to the bug being introduced in the GUI engine.

**Comment by Goldenfreddy0703** [comment] 2022-07-19 11:20
> However, it is not for Android

About that, I actually found an android version in the test builds and tested it and everything seemed to be working.

**Comment by Goldenfreddy0703** [comment] 2022-07-19 15:02
Ahh, i understand, Nexus is amazing so far, i have not had a single crash and everything is working and loading faster just fine for me. One of my favorite features that came with Nexus is that the Voice search is fixed and works really well and that we can now update from any repository thanks to that issue i noticed.
