### ISSUE TITLE
[BUG] fullscreen widget fanart focus

### ISSUE THREAD

**Issue by A3006B** [jurialmunkey/skin.arctic.horizon.2#724] opened 2023-01-02 15:55 UTC
### Skin section

Home Widgets

### Current Behavior

When focus is on a Home Screen menu item button, the fanart of the fullscreen widget seems to override local artwork and pull from tmdb. Clicking down onto the fullscreen widget then shows the local fanart artwork

### Expected Behavior

Local fanart should show when focus is on the menu item 

### Steps To Reproduce

Go to menu item
Fanart will show tmdb fanart instead of local fanart
Clicking down onto widget then shows local fanart

### Screenshots and Additional Info

https://user-images.githubusercontent.com/114344593/210254097-7a93ffdc-9a16-4ac2-bf17-5f69ec86e65f.MOV

I have cleared thumbnails and texture db and issue still persists

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-01-02 23:40
I can't reproduce this one on Nexus. Are you on Matrix or Nexus?

**Comment by A3006B** [comment] 2023-01-02 23:41
Hi jurial :)
Matrix 19.5

**Comment by jurialmunkey** [comment] 2023-01-02 23:44
I think it might be related to a Matrix bug with nested variables which was fixed in Nexus. I'm double checking the skin code now to confirm but if that's the issue there's not much I can do about it.

**Comment by A3006B** [comment] 2023-01-02 23:45
Fair enough, it only recently started doing it a couple weeks back, can’t remember for certain if it was happening before 19.5 though

**Comment by jurialmunkey** [comment] 2023-01-03 00:05
@A3006B - Oh wait, are you using "Stretch" not "Blur"? I think I realised what the issue might be related to.

**Comment by A3006B** [comment] 2023-01-03 00:08
Yeah, stretch with keyart, might be flixart and stretch

**Closed** 2023-01-03 00:10 UTC
Labels: bug

**Comment by jurialmunkey** [comment] 2023-01-03 00:13
Ah yep I see exactly what the issue is. Can reproduce with Stretch+FlixArt.

The fix will also need the fix to TMDbHelper from the context menu issue. I'll push a repo update for both soon -- just have a few extra things I want to add first.
