### ISSUE TITLE
[BUG] Skin not returning to show section after playback 

### ISSUE THREAD

**Issue by IG2022** [jurialmunkey/skin.arctic.horizon.2#490] opened 2022-09-29 13:03 UTC
### Skin section

Library Views

### Current Behavior

After playback ends for TV shows I am getting blank screen rather than the skin returning to the section where I started to play the show from. This has been happening with tv shows quite a bit and I have to back out and come back to the section to play the next episode. I've tired this with different views and the same issue happens I've used big landscape and media info list views and both have the same issue. Using the default Kodi skin I don't get this behavior. 

### Expected Behavior

After playback ends I should be sent back to the section I was in when I played the episode and I should be able to select the next episode. 

### Steps To Reproduce

1 Go to TV show list 
2 play tv show all the way through
3 after show ends get the busy spinner and blank screen. 

### Screenshots and Additional Info

Log: 
https://paste.kodi.tv/tetoguyebi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment] 2022-09-29 13:52
I've experienced this behavior as well occasionally, when a episode finishes I get a blank screen back out and back in it goes back to normal

**Comment by jurialmunkey** [comment] 2022-10-02 06:45
What do you mean by "not returning"? Is the screen black? Can you get me a video of this behaviour?

**Comment by sith1ord70** [comment] 2022-10-02 07:44
I've had the same problem, when you try to go back to main screen after viewing a tv show or movie. Sometimes it go black screen and crash when I first load Kodi 19.4 (Nvidia Shield)

**Comment by IG2022** [comment] 2022-10-02 12:18
> What do you mean by "not returning"? Is the screen black? Can you get me a video of this behaviour?

For example if I am watching season 1 of a tv show and I play episode 1 after episode 1 ends I should be redirected to season 1 episode list but instead get a blank screen. The screen isn't black but has the background setting that I have selected. I have to then back out and select season 1 again to get the episode list and choose the next episode. This doesn't always happen and it only happens when I watch an episode all the way through.  The next time it happens I'll try get you a video.

**Comment by jurialmunkey** [comment] 2022-10-02 14:02
So the viewtype is hidden, is that what you mean? But the clock and heading are still visible?

e.g. does it look like this? Or is the clock and heading hidden too? (assuming that you haven't hidden those yourself of course!)

![Honeyview_screenshot00170](https://user-images.githubusercontent.com/4618719/193458072-eca0da64-70ca-48e8-981d-a36b48e3d4e6.jpg)

**Comment by xyzfre** [comment] 2022-10-02 14:06
> So the viewtype is hidden, is that what you mean? But the clock and heading are still visible?
> 
> 
> 
> e.g. does it look like this? Or is the clock and heading hidden too? (assuming that you haven't hidden those yourself of course!)
> 
> 
> 
> ![Honeyview_screenshot00170](https://user-images.githubusercontent.com/4618719/193458072-eca0da64-70ca-48e8-981d-a36b48e3d4e6.jpg)
> 
> 
> 
> 

On my end that is EXACTLY the screen I get after a episode Finishes this happens occasionally if I back out and go back in the episodes show up again

**Comment by IG2022** [comment] 2022-10-02 14:36
> So the viewtype is hidden, is that what you mean? But the clock and heading are still visible?
> 
> e.g. does it look like this? Or is the clock and heading hidden too? (assuming that you haven't hidden those yourself of course!)
> 
> ![Honeyview_screenshot00170](https://user-images.githubusercontent.com/4618719/193458072-eca0da64-70ca-48e8-981d-a36b48e3d4e6.jpg)

Yes that's correct this is exactly how it looks, just the clock and heading are visible but nothing else is at which point I need to back out of the section and go back in.

**Comment by jurialmunkey** [comment] 2022-10-03 00:08
Okay interesting. There's two main conditions that happens on Container.NumItems=0 or the recommendations window HideView property is set.

When this happens, how far back do you have to go to fix it? Do you need to go all the way out to the home screen or only up one level (e.g. from episodes to seasons) ?

Reason I ask is that there's a fail safe built into the home screen to clear the HideView property in case the recommendations window doesn't close properly. So if you have to go that far back then the culprit is the property; whereas if you only go up one level it is possible it's some weird platform specific quirk with Container.NumItems

**Comment by xyzfre** [comment] 2022-10-03 01:52
On my end it's ,only up one level

**Comment by IG2022** [comment] 2022-10-03 03:39
> Okay interesting. There's two main conditions where that will happen: either when Container.NumItems=0 or if the recommendations window has set the HideView property.
> 
> When this happens, how far back do you have to go to fix it? Do you need to go all the way out to the home screen or only up one level (e.g. from episodes to seasons) ?
> 
> Reason I ask is that there's a fail safe built into the home screen to clear the HideView property in case the recommendations window doesn't close properly. So if you're having to go all the way back to home, that points to an issue with the property. Whereas only needing to go up one level to seasons points to an issue with Container.NumItems count.

I just have to go back one level. If it's a shortcut menu on the home screen like my next up episodes where there is no seasons view (just individual episodes) then I have to go back to the home screen but if there is a seasons view then I just need to go back one level to the seasons and chose the season I was on.

**Comment by jurialmunkey** [comment] 2022-10-03 05:20
Okay sounds like Kodi has some issue with updating the Container item count for some reason. Can you try v0.5.14 (latest) and see if it still happens.

**Comment by IG2022** [comment] 2022-10-03 10:21
> Okay sounds like Kodi has some issue with updating the Container item count for some reason. Can you try v0.5.14 (latest) and see if it still happens.

I can't say for sure (since the issue was not really consistently happening) but I am fairly sure the latest update solved this issue I've tired a couple of episodes and everything has reloaded the way it should . I'll keep an eye open over the next day or so and incase it appears again.

Thanks you! 

Thanks!

**Comment by xyzfre** [comment] 2022-10-03 12:24
Same here played a couple episodes and also stop midway and now everything loads properly thank you @jurialmunkey and @IG2022 for bringing up this issue

**Comment by IG2022** [comment] 2022-10-03 14:02
After living with the update a little I've found that another issue has come up. When the episode ends now it doesn't go to a blank screen but loads an empty list with the landscape media list view, there is no content on this list. When I  Back out and come back in it loads the content again in the correct view.

**Comment by xyzfre** [comment] 2022-10-03 15:47
I know I saw this somewhere and it finally hit me looks like on discord somebody had posted a similar issue A couple weeks ago

**Comment by xyzfre** [comment] 2022-10-03 15:47
![image](https://user-images.githubusercontent.com/49699869/193620768-502f31a1-b6ac-4a87-9f05-12ecfdbb0d45.jpeg)

**Comment by xyzfre** [comment] 2022-10-03 15:49
![image](https://user-images.githubusercontent.com/49699869/193621216-628e2431-1895-408f-8a22-873760d7217d.jpeg)

**Comment by xyzfre** [comment] 2022-10-03 17:45
![image](https://user-images.githubusercontent.com/49699869/193641472-a5f1ca9e-7e5e-4044-b257-2cb9124efc3e.jpeg) this only happens sometimes but this is the screen I get like the post above I use big landscape roll ,, and occasionally when an episode finishes it changes to this view backing out and going back in brings it back to my original view big landscape roll

**Comment by xyzfre** [comment] 2022-10-03 21:44
Been doing more testing, Just  to keep you guys posted this recent update has improved this issue @jurialmunkey  once a episode finishes it does load quicker on my end ,, and off topic also noticed clear logos on home screen transition much faster and smoother on my Nvidia Shield 2019 Pro GREAT WORK ✊🏼

**Comment by jurialmunkey** [comment] 2022-10-05 08:59
@xyzfre @IG2022 - Can you test v0.5.17. I'm hoping that I've managed to fix #506 -- which was caused by the fix for this issue) -- without causing this issue again

**Comment by xyzfre** [comment] 2022-10-05 11:57
Yep definitely fixed issue 506 working perfect 👌🏼 ,with the playback issue did some testing this morning when an episode finish it did load faster no blank screen ,,I will keep you posted thank you for all your hard work and dedication AH2 is the BEST

**Comment by IG2022** [comment] 2022-10-05 14:01
> @xyzfre @IG2022 - Can you test v0.5.17. I'm hoping that I've managed to fix #506 (which was caused by the fix for this issue) without causing this issue again

Hey thanks for looking into this further. It's working alot better than before still get the blank screen for a second or two after playback ends but then the loading spinner comes up again and the correct view type shows up. Definitely don't need to back out anymore. It's weird that this is only a android issue.

Anyway thanks again for looking into this. You've made a real difference with the last update I appreciate it.

**Comment by xyzfre** [comment] 2022-10-05 18:26
Agree!💯 this update really made a big improvement with the playback issue GREAT WORK @jurialmunkey

**Comment by jurialmunkey** [comment] 2022-10-06 12:35
Okay great. Thanks for testing.

I don't think I can do anything about the delay - but as long as it isn't blocking the container from the loading, that's the important thing.

**Closed by jurialmunkey** 2022-10-06 12:35 UTC
Labels: bug

**Comment by IG2022** [comment] 2022-10-07 04:40
> Okay great. Thanks for testing.
> 
> I don't think I can do anything about the delay - but as long as it isn't blocking the container from the loading, that's the important thing.

Thanks for sorting this out, the delay went away after restarting Kodi all works well now.
