### ISSUE TITLE
[BUG] Kodi Crashes on EPG fast-scrolling

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#386] opened 2022-07-30 08:15 UTC
### Skin section

Other

### Current Behavior

This bug happens for a longer time - probably since the very beginning. If I open EPG view and long press up or down to scroll through the list sooner or later kodi will crash (it takes 5 to 30 seconds usually). 

### Expected Behavior

fast-scrolling in EPG shouldn't crash Kodi

### Steps To Reproduce

1. go to EPG
2. long-press up and down and hold it
3. see epg list scrolling
4. wait for a crash - it should happen sooner or later

### Screenshots and Additional Info

- I tested this strange behaviour on Linux / CoreElec and MacOs.
- I tested this with and withoud video playback in the background
- I testen this with various EPG views
- my PVR channel list has 198 channels
- this doesn't happen in Estuary

I will attach crashlog later today with active window component diagnostic info. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by krzysztofwinnik** [comment] 2022-07-30 13:36
Please find 2 log files attached. 
@jurialmunkey - any idea what causes that crash?
[kodi_crashlog_20220730152334.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9226560/kodi_crashlog_20220730152334.log)

[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9226562/kodi.old.log)

**Comment by krzysztofwinnik** [comment] 2022-08-03 10:58
Hi @jurialmunkey, I'sure you are superbusy and this issue is not on your priority list, but could you just confirm this is something you will look into? Or does this look more like a skin engine bug, which I should report to Kodi devs? Thank you

**Comment by jurialmunkey** [comment] 2022-08-03 12:42
I'm not sure what that cause would be. I couldn't reproduce it myself

**Comment by krzysztofwinnik** [comment] 2022-08-03 16:54
I was afraid you would say so... Fortunatelly the bug is not critical. Many thanks anyway.

Oo, could we have this issue left open just in case anyone else reports simmilar problem... or maybe even a solution?

**Comment by AstaFatherSatan** [comment] 2022-08-11 12:30
i have the issue on my celeron laptop

**Comment by krzysztofwinnik** [comment] 2022-08-11 14:21
Well, it certainly isn't a Celeron issue - my mac has intel i5 and tvbox has amlogic s922x. There must be some other explanation than processor architecture.

**Comment by krzysztofwinnik** [comment] 2022-08-12 09:35
Many thanks @jurialmunkey for your research and recent contextmenu cleanup. Unfortunatelly v0.3.16 (and latest as well) didn't make any change for me in terms of the epg bug.
I've read the discussion you found on xbmc github, but they didn't came to any breakthrough or conclusion. However, they shed some light on the meaning of the bug in kodi log ("ERROR : GetItem: EPG tag (XXX,YYY) not found!
ERROR : GetGridItemPtr: Got no EPG tag (XXX, YYY)"). Apparently it means that EPG data is somehow corrupted for channel XXX. Except for it the fact that same EPG data work just fine with estuary skin for me. They also suggested Kodi Nexus might help. So I tried nexus alpha - with no success, sadly. It seems the root cause for the bug remains unknown.

**Comment by AstaFatherSatan** [comment] 2022-08-12 17:43
this bug doesnt happen on the estuary skin for me.

**Comment by kcook98765** [comment] 2022-09-30 03:29
FYI: This might be related to an issue I posted (with fix on it's way into code) at:

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/pull/884

**Comment by jurialmunkey** [comment] 2022-09-30 03:42
> FYI: This might be related to an issue I posted (with fix on it's way into code) at:
> 
> [jurialmunkey/plugin.video.themoviedb.helper#884](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/pull/884)

@kcook98765 - Unlikely to be that specifically since that particular line of code didn't even exist when this bug was reported -- but does make me think maybe there is something similar with an unmatched parenthesis or bracket hiding somewhere in the skin code.

**Comment by jurialmunkey** [comment] 2023-01-22 05:26
@krzysztofwinnik - Closing this one as you mentioned that it was solved by the _elementtree workaround in TMDbHelper.

Let me know if it happens again but I'm assuming elementtree in Py3.11 was the cause -- which also makes sense as to why I couldn't reproduce myself even in Linux Mint (the version in my VM was running Py3.9).

**Closed by jurialmunkey** 2023-01-22 05:26 UTC
Labels: bug

**Comment by AstaFatherSatan** [comment] 2023-01-23 00:11
Thank you
