### ISSUE TITLE
[Feature] Background Images from Folder

### ISSUE THREAD

**Issue by Dragoopai** [jurialmunkey/skin.arctic.horizon.2#783] opened 2023-01-29 13:57 UTC
### Skin section

Home Widgets

### Feature description

I would like to be able the select the background from a folder. And let the skin pick randomly from this folder.

### Why is this feature needed? Please justify and explain.

I was very confused when I did not find the option because for start up images it was already implemented. I do not understand the limitation for that.

Also I came from "Aeon Nox Silvo" and there you have multiple image option for the default background, for each main menu items and also for the sub menus so I was confused to not see the in this really cool and modern skin. But maybe I am wrong and that's just because I am a newbie regarding Kodi! :)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by DROIDshield** [comment] 2023-06-06 00:05
This is something I was going to ask if this would be possible to do. I have already got a set image that shows up... but I'd love to be able to point the background to a folder rather than just one image and so it picks like the startup images, a different background whenever it shows up.

@jurialmunkey any chance of this being implemented?

**Comment by jurialmunkey** [comment] 2023-06-27 12:43
Duplicate of https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/936

If you set a main menu item fullscreen widget to a picture source and set no other widgets, it will use the picture source as a background.

**Closed by jurialmunkey** 2023-06-27 12:43 UTC
Labels: enhancement
