### ISSUE TITLE
Nexus HDR tags

### ISSUE THREAD

**Issue by Shawn9347** [jurialmunkey/skin.arctic.horizon.2#810] opened 2023-02-12 09:23 UTC
### Skin section

Library Views

### Feature description

Kodi 20 now includes hdr tags. This is a cool feature I would like to see in Arctic horizon 2. 

### Why is this feature needed? Please justify and explain.

It's very helpfull. And it looks cool.

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/48714886/218302890-acfc4019-f638-4d8c-88b5-833e1290a4e4.png)

![image](https://user-images.githubusercontent.com/48714886/218302895-75448d07-97c1-4b8f-91db-0bc7ecd0557c.png)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2023-02-12 11:39
Duplicate of #610

**Closed by jurialmunkey** 2023-02-12 11:39 UTC
Labels: enhancement
