### ISSUE TITLE
No option to change channel group in PVR 

### ISSUE THREAD

**Issue by elite-graphix** [jurialmunkey/skin.arctic.horizon.2#132] opened 2022-06-10 12:38 UTC
Hi, in AH1 there is an option to change pvr channel group by pressing left or right key on remote when watching pvr channel. in AH2 its showing all channels in row without channel group selection, am i missing something here or its by design? could you please add this functionality if its by design? thanks a lot for a great skin.

**Comment by elite-graphix** [comment] 2022-06-10 14:43
Yes, this functionality is there in AH1 as well i dont find it in AH2

**Comment by derrgoo** [comment] 2022-06-10 14:45
Yes- I find it very handy which I think and hope he will add in time. 👍

**Comment by jurialmunkey** [comment] 2022-06-10 16:41
Duplicate of #71

**Closed by jurialmunkey** 2022-06-10 16:41 UTC
