### ISSUE TITLE
[Feature] Add an option for "Expand information" in info

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon.2#238] opened 2022-06-19 15:52 UTC
### Is your feature request related to a problem? Please describe.

When looking at info, There's no plot/info for each item.

### Describe the solution you'd like

An option to add it like the "Expanded info" spot in info area. Maybe you can add it like the option to always have a stop button because I know not everyone likes the info/plot showing.

### Screenshots and Additional Info

What is currently the option. 
![Screen Shot 2022-06-19 at 10 29 47 AM](https://user-images.githubusercontent.com/43726430/174489586-527c1082-719d-47cb-a969-039976426c0d.png)
![Screen Shot 2022-06-19 at 10 33 08 AM](https://user-images.githubusercontent.com/43726430/174489589-add93b13-d4de-4848-a338-59ede16c2583.png)

What I'm hoping to see but obv not in the widget area. 
![](https://user-images.githubusercontent.com/43726430/173698378-7a44982b-1418-4200-8922-9768455bf757.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2022-06-20 01:34
Duplicate of #182

**Closed by jurialmunkey** 2022-06-20 01:34 UTC
Labels: enhancement
