### ISSUE TITLE
[Request] Option for Auto Hide OSD

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon.2#59] opened 2022-06-05 19:36 UTC
As the title says, there's no option for auto hiding the OSD when playing content.

**Comment by jurialmunkey** [comment] 2022-06-06 09:25
Duplicate of https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/30

**Closed by jurialmunkey** 2022-06-06 09:25 UTC
