### ISSUE TITLE
Blank trailer in videoinfo dialog

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#17] opened 2022-06-04 16:05 UTC
First thing first, amazing skin as always from you mate 😍 Many thanks!
Totally love the new pop-up context menu, absolutely brilliant 👌

1 query: Cast Info- will it be possible to show the movies/TV Shows the actor is associated with underneath his personal info/career history?

1 observation: Trailer- please see the screen record https://streamable.com/hovutr
The trailer is not visible in the panel even though it's playing in the background

**Comment by jurialmunkey** [comment] 2022-06-05 04:04
> query: Cast Info- will it be possible to show the movies/TV Shows the actor is associated with underneath his personal info/career history?

Already available:

- Press down in info dialog to view cast and then click on a cast member to open their info page. 
- Press down from the cast member info page to scroll widgets of the movies/tvshows etc. that they are cast/crew in.

> 1 observation: Trailer- please see the screen record https://streamable.com/hovutr The trailer is not visible in the panel even though it's playing in the background

What platform is this on? Does this work correctly in other skins with video in a pop-up / replacing fanart?

Trailer window works for me, but it is possible that whatever platform you're on doesn't allow video overlays (i.e. only plays fullscreen video, not video replacing fanart or in a pop-up).

**Comment by onlytanmoy** [comment] 2022-06-05 07:26
Please find my further observations:

Cast Info- Pressing the down key of my Shield remote does nothing, pressing the up key shows more info. I also tested with another Bluetooth keyboard, same issue.
Screen record for ref: https://streamable.com/95gwva

Windowed/pop-up Trailer- I am using Shield Pro 2019. Yes, this works correctly in Cosmic skin from heppen. This is my setting for AH2 skin: https://imgur.com/a/2cgoga7  Hope that is fine?

**Comment by jurialmunkey** [comment] 2022-06-05 08:12
> Cast Info- Pressing the down key of my Shield remote does nothing, pressing the up key shows more info. I also tested with another Bluetooth keyboard, same issue. Screen record for ref: https://streamable.com/95gwva

That's a different method to what I said. These are the steps that I said:

- Press info on movie (you didn't press info, you pressed context > similar > cast) 
- Press down to view cast from movie info
- Click cast member to open info
- Press down from cast member info to view movies/shows

> Windowed/pop-up Trailer- I am using Shield Pro 2019. Yes, this works correctly in Cosmic skin from heppen. This is my setting for AH2 skin: https://imgur.com/a/2cgoga7 Hope that is fine?

Those settings aren't related to trailers. That just changes library view appearance.

I'm not familiar with Cosmic. Does it have a windowed Trailer?

**Comment by onlytanmoy** [comment] 2022-06-05 08:21
I followed the steps for cast info as you said, please see https://streamable.com/p090ek
Press down triggers nothing at my end.

I don't have Cosmic installed now, will do that and share the screen record.

**Comment by jurialmunkey** [comment] 2022-06-05 08:36
> I followed the steps for cast info as you said, please see https://streamable.com/p090ek Press down triggers nothing at my end.
> 


Ah, sorry, you're completely right -- it _was_ working before but now it isn't! I accidentally broke it whilst fixing something else.

Should be fixed now in 0.1.2 -- that should also allow you to go the other way via "Context > Similar > Cast" now. And also if you use row view, should be able to go straight to Movies/Shows for the person by pressing down from the scroll bar too.

**Comment by onlytanmoy** [comment] 2022-06-05 08:37
Ok, great, thanks mate.

Please see screen record from Cosmic skin: https://streamable.com/5je17i

**Comment by jurialmunkey** [comment] 2022-06-05 09:05
> Ok, great, thanks mate.
> 
> Please see screen record from Cosmic skin: https://streamable.com/5je17i

Thanks, yeah that's definitely windowed. I looked at the code for Cosmic, and the only significant difference that I noticed is that there is no animation on the videowindow overlay.

It triggered a vague memory of there being some issue with animations and videowindow overlays on Android, so my guess is that the fade or slide animation gets stuck at 0% so it never becomes visible.

Could you try 0.1.3 from the releases? I've moved the animation so it won't apply to the video overlay and I'm hoping that will fix it.

**Comment by onlytanmoy** [comment] 2022-06-05 09:40
Just tried out v0.1.3, no luck with the windowed trailer as you can see from the screen record: https://streamable.com/eb1wdb

**Comment by onlytanmoy** [comment] 2022-06-05 10:27
Cast-context menu-browse lists-cast in movies   not working any more
Please see this screen record: https://streamable.com/43801v
It worked in v0.1.2 though, so something in v0.1.3 broke it :(
Please fix it. Thanks.

**Comment by jurialmunkey** [comment] 2022-06-05 11:16
> Cast-context menu-browse lists-cast in movies not working any more Please see this screen record: https://streamable.com/43801v It worked in v0.1.2 though, so something in v0.1.3 broke it :( Please fix it. Thanks.

Are you sure that this worked in the Recommendations window specifically? I don't think it did.

**Comment by onlytanmoy** [comment] 2022-06-05 11:35
Sorry for the confusion mate. Just did the below tests on v0.1.3
This navigation works: https://streamable.com/w4jmg2
This navigation doesn't: https://streamable.com/iofxh6
so the later needs a fix, probably you already got this covered in your Todo list.

**Comment by jurialmunkey** [comment] 2022-06-05 15:25
> Sorry for the confusion mate. Just did the below tests on v0.1.3 This navigation works: https://streamable.com/w4jmg2 This navigation doesn't: https://streamable.com/iofxh6 so the later needs a fix, probably you already got this covered in your Todo list.

No worries!

Yeah its because the Dialog is still active so it prevents TMDbHelper from updating the container. I think its something I might need to add in TMDbHelper to get it to work rather than in the skin.

**Comment by onlytanmoy** [comment] 2022-06-05 16:38
Nice to see you have already figured out the root cause 👍

In the Player/OSD section of your Todo list please consider adding: "Auto-close player controls after 3 secs" if its not too much work. At the moment you need to click the remote back button to make the player control disappear.

**Comment by dm2912** [comment] 2022-06-05 21:58
The trailer issue Isn't restricted to android. same issue in Corelec

![screenshot00024](https://user-images.githubusercontent.com/25871666/172072098-4d64bec0-eaf9-4222-9700-30c70e074539.png)

O/S: CoreELEC (official): 19.5-Matrix_rc1

**Comment by alKODIque** [comment] 2022-06-06 09:41
> I'm a bit stumped on what the cause could be. Does this work correctly in AH1?

Work just fine for me in AH1 👍

**Comment by jurialmunkey** [comment] 2022-06-06 09:49
> > I'm a bit stumped on what the cause could be. Does this work correctly in AH1?
> 
> Work just fine for me in AH1 👍

@alKODIque with the small trailer window (not just fullscreen)? That's really interesting

**Comment by alKODIque** [comment] 2022-06-06 09:52
Yeah..
Windowed view only.
And if you see on my video, when I go full screen, it ''fast forward'' to reach the playback.
In AH1, I don't have any issue in both case

**Comment by jurialmunkey** [comment] 2022-06-06 10:36
Okay this is a real long shot based on the fact that it works in AH1 - I've moved the trailer code out to a separate include because that's the only significant difference I could see between the method in AH1 and AH2.

Could someone test 0.1.9 and see if that helps
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.9

**Comment by alKODIque** [comment] 2022-06-06 10:39
I just ionstalled v1.9 and it did not resolved the issue for me :(

**Comment by ShibajiCh** [comment] 2022-06-06 10:46
> Okay this is a real long shot based on the fact that it works in AH1 - I've moved the trailer code out to a separate include because that's the only significant difference I could see between the method in AH1 and AH2.
> 
> Could someone test 0.1.9 and see if that helps https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.9

Hi @jurialmunkey,

No, the fix didn't work. It's still showing black window. 🙁

**Comment by dm2912** [comment] 2022-06-06 11:30
No change with 0.1.9 here in CoreELEC

And to confirm, trailers work in window with AH1 in CE

**Comment by alKODIque** [comment] 2022-06-06 11:34
Cool!
Your last commit resolved it for me! 🎉

**Comment by jurialmunkey** [comment] 2022-06-06 11:36
> Cool! Your last commit resolved it for me! 🎉

Amazing! Thanks for testing.

Your comment about the stuttering made me think that possibly the two are were connected. Audio stuttering is due to there not being a background video window as I hadn't sorted that out yet, so I just hid one behind the background for the time being. Looks like it solved both issues!

**Comment by jurialmunkey** [comment] 2022-06-06 11:37
@dm2912 @onlytanmoy @ShibajiCh - Could you also test 0.1.10 and confirm that it fixes for you?
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.10

**Comment by onlytanmoy** [comment] 2022-06-06 11:51
@jurialmunkey  working like a charm mate https://streamable.com/7vu772
Hope you enjoy the coffee I got for you now :)

Any thoughts on this? In the Player/OSD section of your Todo list please consider adding: "Auto-close player controls after 3 secs" if its not too much work. At the moment you need to click the remote back button to make the player control disappear.

**Comment by ShibajiCh** [comment] 2022-06-06 11:52
Hi @jurialmunkey,

Yes, I can confirm that the trailer window is working fine in version 0.1.10. However, could you please auto hide the text above the window after a few seconds? That'll make it look less distracting. What do you think?
![IMG20220606172054](https://user-images.githubusercontent.com/65297828/172155489-2586dc0b-e25e-4d8e-bc75-c7aedd9b947c.jpg)

**Comment by dm2912** [comment] 2022-06-06 11:54
Confirm 0.1.10 fixes it in CoreELEC

**Closed** 2022-06-06 13:21 UTC

**Comment by ShibajiCh** [comment] 2022-06-06 13:29
> Excellent, thanks everyone for testing and bearing with me while I tried a few things out. We got there in the end! 🎉

You're welcome @jurialmunkey ! 🙂
That's the least we could do. All thanks to you for this beautiful skin!
