### ISSUE TITLE
Autostart trailer playback in full screen mode and (optionally) the ability to change the background brightness (background of video content)

### ISSUE THREAD

**Issue by Whiteripd0** [jurialmunkey/skin.arctic.horizon.2#218] opened 2022-06-17 22:20 UTC
After you added the ability to play video in the background, I noticed that it, like fanart, is not shown in full screen mode .. (This function only works in video content libraries!) But unfortunately, for some reason, only there) 
 An idea came up that you might like it!) Can you please add a feature that would include the autorun trailer in full screen mode? For some reason, I think this is possible, since in many skins this worked without problems) (Cosmic, Netflix, and even Arctyc Zephyr) If you added this function, I would be very grateful and  happy!)
 It so happened that I configured it in the ' Customize home menu'' to full screen mode and even made widgets in full screen mode) Therefore, 90% of the use I use only full screen mode!) Therefore, I would very much like that the functions that you add also work in this mode:) 
Also, sorry for the impudence!) Well, I would like to know if it is possible to add (optionally) the function of changing the background brightness (including multifanart) since the background is very faded even with increased brightness on the TV (Therefore, I would very much like something like that) 
Sorry that I can’t find any errors or bugs .. In my opinion, everything works fine except for what I described above .. Well, I dug deep enough)) And for some reason I didn’t find any serious problem in use) And in general, what thats a problem!)

**Comment by jurialmunkey** [comment] 2022-06-18 01:30
Duplicate of #185

**Closed by jurialmunkey** 2022-06-18 01:30 UTC
Labels: enhancement
