### ISSUE TITLE
[BUG] Widgets won't load on first screen (Nexus v20 on TvOS)

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#225] opened 2022-06-18 14:15 UTC
### Current Behavior

Seeing a strange issue on Nexus v20 on TvOS (not sure if this would also happen on other platforms).  Widgets (from any addon) don't load on the very first (left) page of the menu.  They load fine on all other menu pages.  And the very same menu page will then load widgets fine if I insert a menu page to the left of it.  On the first menu page, fullscreen widgets will load, but no standard widgets will load - they just show the loading spinner infinitely.

### Expected Behavior

Widgets should load on first menu page.

### Steps To Reproduce

1.  Install Kodi Nexus v20 Alpha on TvOS
2. Setup AH2 with widget(s) on the first (top/left) menu page.
3. Reload skin and see if widget(s) load on first page.
4. Notice that widgets load successfully on all other pages.

### Screenshots and Additional Info

Log file:  [https://paste.kodi.tv/xurijohuja](https://paste.kodi.tv/xurijohuja)

My current widgets are from TMDB Helper, but I've also tried widgets from other video addons with the same results. 

You can see in the screenshot below that the widgets never load on the first (left) menu page (this has been loading for ~10 minutes):

![Screen Shot 2022-06-18 at 10 10 41 AM](https://user-images.githubusercontent.com/33561812/174442304-d0abf119-dd22-4aa5-bbdb-e8bbab661037.png)

In the second screenshot below, notice that I've inserted a page called Home as the first (left) menu page, and now the very same Shows page loads the widgets successfully:

![Screen Shot 2022-06-18 at 10 11 36 AM2](https://user-images.githubusercontent.com/33561812/174442405-ebbe036f-3620-4564-b37c-54f9a96d2e51.png)
 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-06-18 17:24
Could you get me your 1080i/script-skinshortcuts-includes.xml file from the skin folder?

All those AttributeErrors I'm pretty sure skinshorcuts isnt building tge template correctly and there's probably a messed up id

**Comment by eengert** [comment] 2022-06-18 18:14
Ok, I'll get you that file later today.  The only way to get access to that on TvOS is to download the app container through Xcode onto my Mac.  That'll take a while.

In the meantime, I just noticed a skinshortcuts error while I was moving around in Kodi so I grabbed this from the latest log in case it helps:

2022-06-18 14:05:57.377 T:41054   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                                   Error Contents: no element found: line 1, column 0
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/5CB2D904-DD77-4357-9320-FFD0C0D02C0D/Library/Caches/Kodi/addons/script.skinshortcuts/default.py", line 3, in <module>
                                                       skinshortcuts.Main()
                                                     File "/private/var/mobile/Containers/Data/Application/5CB2D904-DD77-4357-9320-FFD0C0D02C0D/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/skinshortcuts.py", line 58, in __init__
                                                       XML.buildMenu( self.MENUID, self.GROUP, self.LEVELS, self.MODE, self.OPTIONS, self.MINITEMS )
                                                     File "/private/var/mobile/Containers/Data/Application/5CB2D904-DD77-4357-9320-FFD0C0D02C0D/Library/Caches/Kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 55, in buildMenu
                                                       tree = xmltree.fromstring( f.read() )
                                                     File "/private/var/containers/Bundle/Application/4F06B55B-1407-4D8C-B4C3-4AD1672C52FD/Kodi.app/Frameworks/lib/python3.9/xml/etree/ElementTree.py", line 1345, in XML
                                                       return parser.close()
                                                   xml.etree.ElementTree.ParseError: no element found: line 1, column 0
                                                   -->End of Python script error report<--

**Comment by eengert** [comment] 2022-06-18 19:20
Here is the file you requested.  Note that this is after inserting the "dummy" Home menu item.  It's the Shows menu item (which is second in this particular file) that has the widgets which won't load when the page is in the first position.

[script-skinshortcuts-includes.xml.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8934174/script-skinshortcuts-includes.xml.zip)

**Comment by eengert** [comment] 2022-06-18 19:51
I just discovered something…I deleted the “dummy “ Home menu item so that Shows is my first menu item (which is what I ultimately want).  I re-launched Kodi and left it for a bit , but the widgets weren’t loading.  Then I navigated left to the Search and then immediately navigated back to the right to my Shows menu page and the widgets were loaded.  I tested that a few more times and it works every time.  Strangely that doesn’t work if I navigate to the right and then back to the first menu page.

**Comment by eengert** [comment] 2022-06-18 20:58
Here is the file with my preferred home menu config, in case it helps.  I also verified that this issue happens for any menu page that I put in the first position.  Also, this wasn't an issue earlier.  Widgets were loading properly a week or two ago using earlier versions of AH2.  Other things have changed about my setup since then, so it might not be anything that changed in AH2, but I just wanted to state that it was working at one point. 

[script-skinshortcuts-includes.xml.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8934336/script-skinshortcuts-includes.xml.zip)

**Comment by jurialmunkey** [comment] 2022-06-19 02:05
Thanks. All this info is really useful! I'll have proper look when I'm at my computer later today  but that error you supplied above pretty much confirms my suspicion that skinshortcuts is failing to build the IDs in the widget template correctly. 

Which would then mean that the skin is hiding the widget and showing the loading icon because Kodi is checking the wrong container status - most likely widgets on multiple pages are sharing the same ids because the main menu id isn't being added.

**Comment by jurialmunkey** [comment] 2022-06-19 14:04
Actually the skinshortcuts includes has built okay even despite the errors. However, using your skinshortcuts includes I cannot reproduce the bug on Matrix -- the exact same layout on Matrix does not cause this issue so I can only surmise that this is a Nexus Alpha bug rather than anything skin related.

**Comment by jurialmunkey** [comment] 2022-06-19 14:22
To that point, I can't reproduce in Nexus Alpha 1 on Windows either (and that's using your skinshortcuts includes). I have to put this down to a platform specific bug for a specific nightly.

I'm going to close this issue for now as I can't reproduce and I can't see any cause for why things aren't working other than the fact that you're using a Nexus nightly on a less common platform.

If you discover relevant information about it, let me know but I can't really see any reason for the skin to be at fault here.

**Comment by jurialmunkey** [comment] 2022-06-28 15:21
@eengert 

Okay I'm able to reproduce and have discovered it occurs in nightlies from 7th Jun onwards. I believe the bug is caused by this PR in Kodi https://github.com/xbmc/xbmc/pull/21387

The issue is that PR causes visibility to be set to false when a conditional fade animation goes below 1% opacity. The problem is that when a container visibility is set to false (rather than just transparent) then it no longer updates -- hence the infinite loading because I use a conditional fade to hide containers whilst they update.

I've lodged a bug report here: https://github.com/xbmc/xbmc/issues/21615

**Comment by eengert** [comment] 2022-06-28 15:23
Thanks. I think it must be in the PR I had to install in order to get TextureMaker working on Nexus.

**Closed** 2022-08-20 07:35 UTC
Labels: bug, external issue
